import Markdown from 'react-markdown';
'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ReactFlow, ReactFlowProvider, Handle, Position, Background, useReactFlow, type NodeProps, type Node, type Edge } from '@xyflow/react';
import { Search, X, Plus, Minus, Maximize, Check, BookOpen, Map, List, ChevronRight, Compass, Link as LinkIcon, RotateCcw } from 'lucide-react';
import '@xyflow/react/dist/style.css';
import { topics, domains, beginner, regionLayout, clusters, MAP_WIDTH, nestedTopicRows, topicCode, type TopicCluster, type Topic, type Domain } from './topics';
import { learningConnections, connectionHandles, edgeTypes } from './roadmap-edges';
type Status='learning'|'familiar'|'completed';
type TopicData={topic:Topic;status?:Status;active:boolean;dim:boolean;onOpen:(id:string)=>void};
function TopicNode({data}:NodeProps<Node<TopicData>>) {const {topic:t,status,active,dim,onOpen}=data; return <div style={{height:t.height}} className={`topic-node ${t.domain} ${t.core?'core':''} ${active?'active':''} ${dim?'dim':''}`}><Handle id="top" type="target" position={Position.Top}/><Handle id="left" type="target" position={Position.Left}/><Handle id="right" type="target" position={Position.Right}/><Handle id="left" type="source" position={Position.Left}/><Handle id="right" type="source" position={Position.Right}/><button className="nodrag" onClick={()=>onOpen(t.id)} aria-label={`Open ${t.title}${status?', '+status:''}`}><span className="node-meta">{topicCode(t)}<span>{status==='completed'?<Check size={13}/>:status==='learning'?'LEARNING':t.core?'CORE':''}</span></span><strong>{t.title}</strong><ChevronRight size={15} className="node-chevron"/></button><Handle id="bottom" type="source" position={Position.Bottom}/></div>}
function RegionNode({data}:NodeProps<Node<{domain:Domain}>>) {const d=domains[data.domain];return <div className={`region ${data.domain}`}><span>{d.code} / FIELD NOTES</span><h2>{d.title}</h2><p>{d.subtitle}</p></div>}
type ClusterData={cluster:TopicCluster;progress:Record<string,Status>;matches:string[];onOpen:(id:string)=>void};
function ClusterNode({data}:NodeProps<Node<ClusterData>>){
 const {cluster:c,progress,matches,onOpen}=data;
 const visible=c.rows.flat().some(id=>matches.includes(id));
 return <section className={`topic-cluster ${c.domain} ${c.id==='mapping'?'transformation-chain':''} ${visible?'':'dim'}`} aria-label={c.title}>
  <Handle id="branch" type="target" position={c.side==='left'?Position.Right:Position.Left}/>
  <h3>{c.title}</h3>
  <div className="cluster-rows">{c.rows.map((row,index)=>{
   if(row.every(id=>Object.values(nestedTopicRows).flat(2).includes(id)))return null;
   const button=(id:string)=>{const topic=topics.find(t=>t.id===id)!;return <button key={id} onClick={()=>onOpen(id)} className={`nodrag numbered-topic ${matches.includes(id)?'':'dim'} ${progress[id]==='completed'?'completed':''}`} aria-label={`Open ${topic.title}${progress[id]?', '+progress[id]:''}`}>
    <span>{<small className="topic-code">{topicCode(topic)}</small>}{topic.title}</span>{progress[id]==='completed'&&<Check size={14}/>}<ChevronRight className="cluster-chevron" size={13}/>
   </button>;};
   const parent=row.find(id=>nestedTopicRows[id]);
   if(parent)return <div key={parent} className="origin-group" style={{height:52+nestedTopicRows[parent].length*60}} role="group" aria-label={`${topics.find(t=>t.id===parent)!.title} and subtopics`}>
    <div className="cluster-row origin-group-title">{button(parent)}</div>
    <div className="origin-group-children">{nestedTopicRows[parent].map((r,i)=><div className="cluster-row" key={i}>{r.map(button)}</div>)}</div>
   </div>;
   return <div className="cluster-row" key={index}>{row.map(button)}</div>;
  })}</div>
 </section>;
}
const nodeTypes={topic:TopicNode,region:RegionNode,cluster:ClusterNode};
const colors={green:'#65845c',roast:'#b06b44',sensory:'#8581a1',practice:'#6e7f82'};
function Atlas(){
 const flow=useReactFlow();const canvas=useRef<HTMLDivElement>(null);const [selected,setSelected]=useState<string|null>(null);const [query,setQuery]=useState('');const [filter,setFilter]=useState<Domain|'all'>('all');const [beginnerOnly,setBeginnerOnly]=useState(false);const [view,setView]=useState<'map'|'list'>('map');const [progress,setProgress]=useState<Record<string,Status>>({});const [ready,setReady]=useState(false);const [notice,setNotice]=useState('');const [zoom,setZoom]=useState(.85);const drawer=useRef<HTMLDialogElement>(null);const search=useRef<HTMLInputElement>(null);const lastFocus=useRef<HTMLElement|null>(null);
 const resetMap=useCallback(()=>{const width=canvas.current?.clientWidth||1000;const scale=Math.min(.85,(width-40)/MAP_WIDTH);flow.setViewport({x:(width-MAP_WIDTH*scale)/2,y:15,zoom:scale},{duration:300});setZoom(scale);},[flow]);
 const current=topics.find(t=>t.id===selected);const completed=Object.values(progress).filter(s=>s==='completed').length;
 const matches=useMemo(()=>topics.filter(t=>(filter==='all'||t.domain===filter)&&(!beginnerOnly||beginner.includes(t.id))&&(`${t.title} ${t.summary}`.toLowerCase().includes(query.toLowerCase()))),[filter,beginnerOnly,query]);
 useEffect(()=>{if(window.matchMedia('(max-width: 700px)').matches)setView('list');try{const saved=JSON.parse(localStorage.getItem('coffee-atlas-progress-v1')||'{}');if(saved&&typeof saved==='object'){setProgress(Object.fromEntries(Object.entries(saved).filter(([id,s])=>topics.some(t=>t.id===id)&&['learning','familiar','completed'].includes(String(s)))) as Record<string,Status>);}}catch{}setReady(true);const read=()=>{const id=location.hash.slice(1);if(topics.some(t=>t.id===id))setSelected(id);else setSelected(null);};read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('coffee-atlas-progress-v1',JSON.stringify(progress));}catch{setNotice('Progress could not be saved in this browser.');}},[progress,ready]);
 useEffect(()=>{if(selected){lastFocus.current=document.activeElement as HTMLElement;drawer.current?.showModal();}else if(drawer.current?.open){drawer.current.close();lastFocus.current?.focus();}},[selected]);
 const open=useCallback((id:string)=>{setSelected(id);history.replaceState(null,'',`#${id}`);},[]);
 const close=()=>{setSelected(null);history.replaceState(null,'',location.pathname+location.search);};
 const focusTopic=(t:Topic)=>{flow.setCenter(t.x+t.width/2,t.y+t.height/2,{zoom:1,duration:500});};
 const setStatus=useCallback((id:string,status:Status)=>setProgress(p=>({...p,[id]:status})),[]);
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const abort=new AbortController();void Promise.resolve(ctx.registerTool({name:'open_roasting_topic',description:'Open a Coffee Roasting Atlas topic by its stable ID.',inputSchema:{type:'object',properties:{id:{type:'string',enum:topics.map(t=>t.id)}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const id=(input as {id?:string})?.id;if(!topics.some(t=>t.id===id))throw new Error('Unknown topic ID');open(id!);return {id,opened:true};}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort();},[open]);
 const nodes=useMemo(()=>{
 const regions:Node[]=(Object.keys(domains) as Domain[]).map((domain)=>({id:`region-${domain}`,type:'region',position:{x:20,y:regionLayout[domain].y},data:{domain},style:{width:1040,height:regionLayout[domain].height},selectable:false,draggable:false,zIndex:-1}));
 return [...regions,...topics.filter(t=>t.core).map(t=>({id:t.id,type:'topic',position:{x:t.x,y:t.y},data:{topic:t,status:progress[t.id],active:selected===t.id,dim:!matches.some(m=>m.id===t.id),onOpen:open},draggable:false,style:{width:t.width,height:t.height}})),...clusters.map(cluster=>({id:cluster.id,type:'cluster',position:{x:cluster.x,y:cluster.y},data:{cluster,progress,matches:matches.map(t=>t.id),onOpen:open},draggable:false,selectable:false,style:{width:cluster.width,height:cluster.height,pointerEvents:'auto' as const}}))];},[progress,selected,matches,open]);
 const edges=useMemo<Edge[]>(()=>learningConnections.map(({source,target,branch})=>({
   id:`${source.id}-${target.id}`,source:source.id,target:target.id,type:'roadmap',
   ...connectionHandles(source,target,branch),data:{branch},
   style:{stroke:branch?colors[source.domain]:'#637b4e',strokeWidth:branch?1.7:2.8,
     strokeDasharray:branch?'3 5':undefined,
     opacity:branch?(clusters.find(c=>c.id===target.id)!.rows.flat().some(id=>matches.some(m=>m.id===id))&&matches.some(m=>m.id===source.id)?.75:0):matches.some(m=>m.id===source.id)&&matches.some(m=>m.id===target.id)?.75:0},
   zIndex:0,
 })),[matches]);
 const start=()=>{setFilter('all');setBeginnerOnly(true);setQuery('');const next=topics.find(t=>t.id===(beginner.find(id=>progress[id]!=='completed')||beginner[0]))!;focusTopic(next);open(next.id);};
 return <main>
 <header className="topbar"><a className="brand" href="#" onClick={close}><span className="brand-mark"><Compass size={24}/></span><span>ROASTING <em>by</em> COORDINATES<small>A FIELD GUIDE TO COFFEE</small><small className="brand-credit">BY COFFEE WITH DONGZE</small></span></a><div className="top-right"><span className="edition">ATLAS / FIRST EDITION</span><button className="dark-button" onClick={start}><BookOpen size={16}/>Start learning</button></div></header>
 <div className="workspace"><aside className="sidebar"><div className="sidebar-top"><span className="eyebrow">YOUR EXPLORATION</span><h1>The roasting<br/><em>atlas.</em></h1><p>A connected guide from green seed to the cup.</p></div><div className="nav-label">EXPLORE THE MAP</div><button className={`nav-item ${filter==='all'?'chosen':''}`} onClick={()=>{setFilter('all');setQuery('');resetMap();}}><Map size={17}/>All territories<span>{topics.length}</span></button>{(Object.keys(domains) as Domain[]).map((d,i)=><button className={`nav-item ${filter===d?'chosen':''}`} key={d} onClick={()=>{setFilter(d);setQuery('');flow.setCenter(MAP_WIDTH/2,regionLayout[d].center,{zoom:Math.min(.85,((canvas.current?.clientWidth||1000)-40)/MAP_WIDTH),duration:500});}}><i style={{background:colors[d]}}/>{domains[d].title}<span>{topics.filter(t=>t.domain===d).length}</span></button>)}<div className="route-box"><h3>Follow the essentials</h3><button className={beginnerOnly?'route-toggle enabled':'route-toggle'} onClick={()=>setBeginnerOnly(!beginnerOnly)} aria-pressed={beginnerOnly}><span className="switch"><i/></span>Beginner path</button></div><div className="progress-block"><div><span>Your progress</span><strong>{completed}<small> / {topics.length}</small></strong></div><progress value={completed} max={topics.length}/><p>Saved on this browser</p></div></aside>
 <section className="map-workspace"><div className="map-heading"><div><div className="eyebrow">THE COFFEE ROASTING ROADMAP</div><h2>Every great roast starts with understanding.</h2></div><span className="prototype-label">PROTOTYPE 01</span></div><div className="toolbar"><div className="search-wrap"><Search size={17}/><input ref={search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a concept…" aria-label="Search concepts"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={15}/></button>}{query&&<div className="search-results">{matches.length?matches.map(t=><button key={t.id} onClick={()=>{focusTopic(t);open(t.id);}}><span>{t.title}<small>{domains[t.domain].title}</small></span><ChevronRight size={15}/></button>):<p>No concepts found. Try “heat” or “cupping”.</p>}</div>}</div><span className="result-count">{matches.length} concepts</span><div className="view-switch"><button className={`mobile-beginner-toggle ${beginnerOnly?'selected':''}`} onClick={()=>setBeginnerOnly(!beginnerOnly)} aria-pressed={beginnerOnly} aria-label="Beginner path" title="Beginner path"><span className={`inline-switch ${beginnerOnly?'enabled':''}`} aria-hidden="true"><i/></span>Beginner</button><button className={view==='map'?'selected':''} onClick={()=>setView('map')} aria-pressed={view==='map'}><Map size={15}/>Map</button><button className={view==='list'?'selected':''} onClick={()=>setView('list')} aria-pressed={view==='list'}><List size={15}/>Outline</button></div></div>

 <div ref={canvas} className={`canvas-shell ${view==='list'?'outline-active':''}`}>
 {view==='map'?<ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} edgeTypes={edgeTypes} onInit={resetMap} defaultViewport={{x:45,y:15,zoom:.85}} minZoom={.3} maxZoom={1.5} nodesConnectable={false} nodesDraggable={false} paneClickDistance={5} panOnScroll zoomOnScroll={false} onMove={(_,v)=>setZoom(v.zoom)}><Background color="#d5d5c8" gap={22} size={1}/></ReactFlow>:<div className="outline">{(Object.keys(domains) as Domain[]).map(d=>{const ts=matches.filter(t=>t.domain===d);if(beginnerOnly)ts.sort((a,b)=>beginner.indexOf(a.id)-beginner.indexOf(b.id));return ts.length?<section key={d}><div className={`outline-title ${d}`}><span>{domains[d].code}</span><h2>{domains[d].title}</h2></div>{ts.map(t=><button className="outline-row" key={t.id} onClick={()=>open(t.id)}><span>{progress[t.id]==='completed'?<Check size={18}/>:<span className="empty-check"/>}</span><span><strong>{t.title}</strong><small>{t.level}{t.core?' · Core concept':''}</small></span><ChevronRight size={17}/></button>)}</section>:null;})}{matches.length===0&&<p>No concepts match your filters.</p>}</div>}
 {view==='map'&&<><div className="map-caption"><span className="legend-core"/> Core concept<span className="legend-line"/> Core path · Topic clusters</div><div className="zoom-controls"><button aria-label="Zoom out" onClick={()=>flow.zoomOut({duration:200})}><Minus size={17}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>flow.zoomIn({duration:200})}><Plus size={17}/></button><span className="divider"/><button aria-label="Fit entire roadmap" onClick={()=>flow.fitView({padding:.06,duration:500})}><Maximize size={16}/></button><button aria-label="Return to start of map" onClick={resetMap}><RotateCcw size={15}/></button></div><div className="pan-hint">Scroll to explore · Pinch to zoom · Select a concept</div></>}
 </div></section></div>
 <dialog ref={drawer} className="topic-dialog" aria-labelledby="topic-title" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}}>{current&&<article className={`drawer ${current.domain}`}><div className="drawer-top"><span className="eyebrow">{domains[current.domain].title}</span><button onClick={close} aria-label="Close topic"><X size={22}/></button></div><span className="topic-level">{`${topicCode(current)} · `}{current.level} · {current.core?'Core concept':'Explore further'}</span><h2 id="topic-title">{current.title}</h2><div className="summary markdown"><Markdown>{current.summary}</Markdown></div><div className="status-label">MY UNDERSTANDING</div><div className="status-options">{(['learning','familiar','completed'] as Status[]).map(s=><button key={s} className={progress[current.id]===s?'selected':''} onClick={()=>setStatus(current.id,s)} aria-pressed={progress[current.id]===s}>{s==='completed'&&<Check size={14}/>} {s[0].toUpperCase()+s.slice(1)}</button>)}</div>{progress[current.id]&&<button className="clear-status" onClick={()=>setProgress(p=>{const next={...p};delete next[current.id];return next;})}>Clear status</button>}<div className="markdown card-body"><Markdown>{current.body}</Markdown></div>{current.prerequisites.length>0&&<><h3>Connect the concepts</h3><div className="related">{current.prerequisites.map(id=><button key={id} onClick={()=>open(id)}>{topics.find(t=>t.id===id)?.title}<ChevronRight size={15}/></button>)}</div></>}<p className="content-note">Prototype field notes · Introductory content, ready for expansion into sourced articles.</p><div className="drawer-bottom"><button onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setNotice('Topic link copied.');}catch{setNotice('Copy the topic link from the address bar.');}}}><LinkIcon size={16}/>Copy topic link</button>{beginner.includes(current.id)&&beginner.indexOf(current.id)<beginner.length-1&&<button className="dark-button" onClick={()=>open(beginner[beginner.indexOf(current.id)+1])}>Next concept</button>}</div></article>}</dialog>
 {notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss"><X size={16}/></button></div>}
 </main>;
}
export default function Home(){return <ReactFlowProvider><Atlas/></ReactFlowProvider>}
