export type Domain = 'green' | 'roast' | 'sensory' | 'practice';
export type Topic = { id: string; title: string; domain: Domain; level: 'Foundation' | 'Intermediate'; core: boolean; summary: string; why: string; exercise: string; misconception: string; prerequisites: string[]; x: number; y: number; width: number; height: number; };
export const domains: Record<Domain, {title:string; subtitle:string; code:string}> = {
 green:{title:'Green potential',subtitle:'Know what you’re starting with',code:'G'},
 roast:{title:'Roast transformation',subtitle:'Turn potential into expression',code:'R'},
 sensory:{title:'Sensory expression',subtitle:'Let the cup guide the next roast',code:'S'},
 practice:{title:'Experiment & repeat',subtitle:'Build a process you can trust',code:'E'},
};
// A deliberately composed graph. Coordinates and content stay separate from UI.
const rows: [string,string,Domain,boolean,string,string,string,string,string[]][] = [
 ['seed-to-cup','Coffee seed','green',true,'Coffee is an agricultural seed whose history shapes what roasting can express. Species, growing conditions, processing, and storage all contribute.','A roast starts with a material, not an empty canvas.','Trace one bag back through its origin, variety, processing, harvest, and storage. Record what is unknown.','Roasting can create any desired flavor in any coffee.',[]],
 ['origins','Origin & terroir','green',false,'Climate, growing conditions, and farming practices interact with genetics. An origin name is useful context, not a complete flavor prediction.','It helps you ask better questions about a lot.','Compare two coffees from the same country with different varieties or processes.','Altitude alone determines quality.',['seed-to-cup']],
 ['varieties','Species & varieties','green',false,'Species and varieties differ genetically. Their expression also depends on the environment and how the coffee is handled.','Genetics provides context for the green material and its possible expression.','Build a side-by-side record of variety, processing, and cup notes for three lots.','A variety label guarantees a particular flavor.',['seed-to-cup']],
 ['processing','Processing methods','green',true,'Washed, natural, and honey describe broad processing families. Fermentation and drying choices vary considerably within them.','Processing helps explain differences you may encounter in the cup.','Taste a washed and a natural coffee, noting other differences that prevent a controlled comparison.','A processing label tells you the full fermentation history.',['seed-to-cup']],
 ['moisture','Moisture content','green',false,'Moisture content is the fraction of a sample’s mass attributed to water. Measurement depends on the instrument and method.','Water affects storage behavior and the energy involved in roasting.','Measure repeated samples from one lot using the same instrument and preparation. Record the spread.','One moisture number tells you the correct charge temperature.',['physical-attributes']],
 ['water-activity','Water activity','green',false,'Water activity describes the availability of water rather than its total quantity. It is distinct from moisture content.','It adds information when evaluating green storage and stability.','Compare moisture and water activity results from the same lots, if both instruments are available.','Equal moisture content means equal water activity.',['moisture']],
 ['density','Density','green',false,'Bulk density includes space between beans. Bean dimensions and size distribution describe different physical properties.','Consistent measurements help characterize and compare lots.','Repeat a bulk-density measurement with a consistent filling method. Note screen size separately.','Bulk density and individual-bean density are interchangeable measurements.',['moisture']],
 ['green-evaluation','Evaluate your green','green',true,'Bring together traceability, physical observations, and a sample roast to form an initial picture of the coffee.','A documented starting point makes later roast decisions more interpretable.','Create a one-page lot record with physical measurements, sample cup notes, and an initial target.','Green measurements replace sensory evaluation.',['moisture','processing']],
 ['target','Define the target','roast',true,'Describe the intended cup and brewing context before adjusting the roast. A target should allow meaningful comparison.','A pleasing curve is not itself a sensory objective.','Write three acceptance criteria for your next roast: desired expression, brew context, and an unwanted characteristic.','There is one universally best roast for a coffee.',['green-evaluation']],
 ['machines','Know your roaster','roast',false,'Drum, fluid-bed, and other roasters differ in heat storage, airflow, agitation, and control response.','Controls and temperature readings do not transfer directly between machines.','Map your machine’s controls and review its operating and fire-safety instructions before roasting.','Matching displayed temperatures matches the same process on different machines.',['target']],
 ['heat-transfer','Heat transfer','roast',true,'Convection, conduction, and radiation transfer heat to the beans. Their contributions depend on the machine and operating conditions.','Changes in energy input affect the roast with delays and interactions.','On a familiar, safely operated machine, compare logged responses to one modest control change.','A burner setting is a direct measurement of heat absorbed by the beans.',['target']],
 ['sensors','Sensors & thermal lag','roast',false,'A probe measures its own response to the surrounding environment. Placement, size, and airflow affect the reading.','Treating readings as observations prevents false precision.','Compare event timing and temperature on repeat roasts before drawing conclusions from small differences.','Displayed bean temperature is the uniform temperature of every bean.',['heat-transfer']],
 ['baseline','A repeatable baseline','roast',true,'Document a roast you can repeat, including warm-up, batch mass, control changes, and cooling. Follow the equipment manufacturer’s safety guidance.','Repeatability makes a later change easier to interpret.','Repeat an established safe roast twice and compare event timings, weight loss, and blind cup notes.','Optimization should come before repeatability.',['heat-transfer']],
 ['phases','Roast phases','roast',true,'Drying, browning, and development are useful observational divisions. Chemical and physical processes overlap across those boundaries.','Events give you reference points for describing a trajectory.','Annotate yellowing, first crack, and drop on a logged roast; note uncertainty in each event.','The start of first crack is the start of all flavor development.',['baseline']],
 ['maillard','Browning & Maillard','roast',false,'Maillard reactions involve amino compounds and reducing sugars. They are one part of a complex network of roasting reactions.','Browning is meaningful, but phase duration alone cannot describe the chemistry.','Compare two controlled roasts and record color and sensory differences without assuming one reaction explains everything.','A longer browning phase always creates more sweetness.',['phases']],
 ['airflow','Energy & airflow','roast',false,'Energy input and airflow influence heat transfer and the removal of moisture and smoke. Their effects depend on the roaster.','The same airflow adjustment can behave differently across machines.','Record airflow settings alongside energy settings in your baseline; change only one factor in a planned comparison.','More airflow always speeds up or always slows down roasting.',['baseline']],
 ['first-crack','First crack','roast',true,'First crack is an audible physical event associated with structural changes and pressure within the beans. Its onset can be gradual.','It is a useful reference event when observed consistently.','Use a consistent onset definition across three roasts and note how confidently you identified it.','First crack occurs at one universal displayed temperature.',['phases']],
 ['ror','Rate of rise','roast',false,'Rate of rise estimates how quickly measured temperature changes. Sampling, smoothing, and probe behavior affect the curve.','It helps describe momentum when interpreted alongside other observations.','Compare the raw temperature trace with two smoothing settings. Notice which apparent features change.','Every crash or flick proves a sensory defect.',['sensors','first-crack']],
 ['endpoint','Roast level & endpoint','roast',true,'Roast color, mass loss, time, and sensory results describe different aspects of the outcome. No single measure captures development.','A consistent endpoint helps isolate differences between experiments.','Measure whole-bean color and mass loss consistently, then compare them with blind cup notes.','Development-time ratio alone defines roast quality.',['first-crack']],
 ['cooling','Cooling & resting','roast',true,'Cooling limits continued thermal change. During resting, gas release and other changes affect how the coffee brews and tastes.','Evaluation timing can change your interpretation of a roast.','Evaluate the same roast at several documented resting intervals using consistent brewing.','Every coffee has the same ideal rest period.',['endpoint']],
 ['cupping','Consistent cupping','sensory',true,'Cupping provides a repeatable preparation for comparing coffees. Use consistent water, grind, ratio, timing, and sample labeling.','Preparation variance can obscure roast differences.','Cup duplicate coded samples of the same roast and compare your notes before revealing them.','A single cup is sufficient to establish a reliable difference.',['cooling']],
 ['water','Water & extraction','sensory',false,'Water composition and brewing conditions influence extraction and perception. They are part of the measurement setup.','Brew differences can be mistaken for roast differences.','Hold water and preparation constant for roast comparisons; investigate brew variables separately.','Every undesirable cup characteristic comes from roasting.',['cupping']],
 ['sensory-language','Sensory vocabulary','sensory',true,'Separate aroma, taste, and texture. Describe intensity and character before deciding whether you like them.','Shared language makes comparisons and feedback more useful.','Describe acidity, sweetness, bitterness, texture, and aftertaste without using a score.','Preference and descriptive intensity mean the same thing.',['cupping']],
 ['blind-tasting','Blind comparison','sensory',true,'Hide sample identities and vary tasting order to reduce expectation and order effects. Repeated comparisons improve confidence.','Knowing a profile can change what you expect to taste.','Ask someone to code two roast samples and include a duplicate. Write notes before revealing the codes.','One successful identification establishes a reliable preference.',['sensory-language']],
 ['attribution','Green, roast, or brew?','sensory',false,'A cup is produced by several linked processes. Use controlled comparisons to investigate the source of a characteristic.','Changing the wrong variable can hide the underlying issue.','For a surprising cup, repeat preparation before making a roast change. Record competing explanations.','A flavor note identifies one specific roast error.',['water','blind-tasting']],
 ['evaluate','Evaluate & update','sensory',true,'Compare the cup to your stated target, acknowledge uncertainty, and choose the next useful test.','Learning is a loop, not a march toward a perfect curve.','Write what changed, what you observed, and one test that could challenge your interpretation.','Every experiment needs to produce a better roast to be useful.',['blind-tasting','target']],
 ['experiment','Change one variable','practice',true,'A controlled comparison starts with a hypothesis and a repeatable baseline. Other conditions should be held as consistent as practical.','It makes cause and effect easier to investigate.','Write a hypothesis, choose one control to vary, and define how you will compare the results.','A single comparison proves causation.',['baseline','evaluate']],
 ['logging','Keep a roast journal','practice',false,'Record lot, machine state, batch mass, controls, events, endpoint measurements, and tasting context.','Useful metadata turns isolated roasts into reusable learning.','Add a short decision log to your next three roasts, including unsuccessful results.','The temperature curve is a complete experimental record.',['baseline']],
 ['scale-up','Translate & scale','practice',false,'Changing batch size or machine changes the system. Sensory equivalence is a more useful goal than matching curves exactly.','A successful sample profile needs validation in production.','Compare a sample and production roast using the same sensory target and evaluation preparation.','Multiplying settings by batch-size ratio produces an equivalent roast.',['endpoint','evaluate']],
 ['qc','Production QC','practice',true,'Define release criteria, sample consistently, and compare production against a reference. Track deviations and corrective actions.','A good roast needs to become a dependable process.','Create a batch record with traceability, endpoint measurements, and a documented sensory release decision.','A matching curve guarantees an identical cup.',['experiment','scale-up']],
];
rows.splice(rows.findIndex(r=>r[0]==='moisture'),0,
 ['physical-attributes','Physical attributes','green',true,'Characterize green coffee with moisture content, water activity, density, and visible defects. These are different observations of the material, not interchangeable quality scores.','A consistent physical record helps compare lots and interpret later roasting observations.','Create a lot sheet with separate entries for moisture, water activity, density, and physical defects.','One physical measurement determines the right roast profile.',['processing']],
);
// Additional field notes are intentionally concise prototype content.
const additions: [string,string,Domain,string,string,string,string][] = [
 ['harvest','Ripeness & harvest','green','seed-to-cup','Harvest selection influences the material entering processing. Ripeness, sorting, and lot separation deserve their own observations.','Ask a supplier how ripeness was assessed and how cherries were sorted.','A harvest date tells you whether every cherry was ripe.'],
 ['washed','Washed','green','processing','Washed processing removes fruit material before the main drying stage. Producers use different methods to remove mucilage.','Describe the sequence of fruit removal, fermentation, washing, and drying for one lot.','Every washed coffee follows an identical process.'],
 ['natural','Natural','green','processing','Natural processing dries coffee within the cherry before the dried fruit layers are removed. Drying management remains essential.','Compare the producer’s drying notes for two natural lots.','Natural processing guarantees one specific fruit flavor.'],
 ['honey','Honey process','green','processing','Honey and pulped-natural processes retain some mucilage during drying. Names and color categories vary between producers.','Ask what a honey label means in the context of a particular farm.','Honey processing means honey was added to the coffee.'],
 ['fermentation','Fermentation','green','processing','Fermentation involves microbial activity during processing. The sequence, duration, and conditions provide more useful context than a label alone.','Record the fermentation steps reported for one lot, distinguishing known conditions from assumptions.','A fermentation label is a complete production record.'],
 ['green-defects','Physical defects','green','moisture','Visible defects can indicate damaged or irregular material. Use a consistent grading method and document the sample size.','Photograph and label visible defects from a green sample; compare with a recognized grading reference.','Every visible irregularity has the same sensory consequence.'],
 ['sample-roasting','Sample roasting','green','green-evaluation','A sample roast supports evaluation of a lot. Consistent preparation helps distinguish green differences from roasting variation.','Compare duplicate samples roasted and cupped with the same procedure.','Sample roasting removes all influence of roasting on the cup.'],
 ['green-storage','Storage & freshness','green','green-evaluation','Packaging, time, and storage conditions affect green coffee. Keep lot history and observations alongside inventory records.','Record packaging, arrival date, and storage conditions for one lot.','Green coffee remains unchanged in storage.'],
 ['drum','Drum roasters','roast','target','Drum machines tumble beans inside a rotating chamber. Their thermal behavior varies with design and operating conditions.','Identify the heat source, airflow path, and agitation controls on a drum machine.','All drum roasters transfer heat in the same proportions.'],
 ['fluid-bed','Fluid-bed roasters','roast','target','Fluid-bed machines use moving air to support and agitate coffee. Air movement and heat delivery are closely connected.','Sketch the air and bean paths for a fluid-bed design.','An airflow setting translates directly between drum and fluid-bed machines.'],
 ['conduction','Conduction','roast','heat-transfer','Conduction transfers heat through contact. Its contribution depends on surfaces, contact conditions, and temperature differences.','Identify where beans contact heated surfaces in your machine.','Contact heating is the only heat source in a drum roaster.'],
 ['convection','Convection','roast','heat-transfer','Convection exchanges heat between moving gas and bean surfaces. Gas temperature and flow conditions both matter.','Trace how heated air reaches the beans and exits your roaster.','Air temperature alone describes convective heat transfer.'],
 ['radiation','Radiation','roast','heat-transfer','Hot surfaces emit thermal radiation. The amount exchanged depends on temperatures, surfaces, and geometry.','Identify which hot surfaces face the bean bed.','Radiation requires direct physical contact.'],
 ['batch-mass','Batch mass','roast','baseline','Batch mass changes the load on the machine and can affect airflow, agitation, and probe exposure.','Record exact green batch mass for each repeat roast.','Half the batch mass always needs half the energy setting.'],
 ['warm-up','Warm-up & equilibrium','roast','baseline','A machine’s thermal state affects its response. A repeatable warm-up routine is part of a repeatable baseline.','Document your manufacturer-approved warm-up and between-batch routine.','One displayed temperature completely describes machine heat storage.'],
 ['roast-color','Roast color','roast','endpoint','Color is an endpoint observation. Whole-bean and ground measurements describe different aspects and require consistent preparation.','Measure repeated samples with the same preparation and instrument.','Equal surface color guarantees an identical cup.'],
 ['weight-loss','Weight loss','roast','endpoint','Mass loss compares green and roasted batch mass. Consistent weighing and handling make comparisons more meaningful.','Calculate (green mass minus roasted mass) divided by green mass for three batches.','Weight loss alone measures flavor development.'],
 ['grind','Grind consistency','sensory','cupping','Grind preparation affects extraction and the repeatability of tasting. Keep equipment, settings, and sample handling consistent.','Prepare duplicate brews using the same grind procedure and compare them blind.','The same dial number means the same grind on every grinder.'],
 ['brew-ratio','Brew ratio','sensory','cupping','The ratio of coffee to brewing water is part of your evaluation method. Record both masses rather than relying on volume estimates.','Weigh coffee and water for every sample in a comparison.','Changing the brew ratio cannot affect a roast comparison.'],
 ['calibration','Taster calibration','sensory','sensory-language','Calibration develops shared references and terminology. Agreement and individual repeatability are related but different goals.','Taste a shared reference and discuss descriptors before comparing scores.','Calibration means every taster must have the same preference.'],
 ['texture','Body & texture','sensory','sensory-language','Texture describes tactile qualities such as perceived weight and smoothness. Separate these observations from aroma and preference.','Describe texture at several temperatures without using flavor-note words.','Heavier body automatically means higher quality.'],
 ['replication','Repeat trials','practice','experiment','Replication helps reveal how much an outcome varies under nominally similar conditions.','Repeat a baseline before attributing a small sensory change to an adjustment.','A single successful trial establishes repeatability.'],
 ['triangle','Triangle tests','practice','experiment','A triangle test presents three coded samples, two alike and one different. Interpreting results requires an appropriate test design.','Practice preparing coded samples and randomizing their order before using results to make a decision.','One correct answer proves a reliable difference.'],
 ['traceability','Lot traceability','practice','qc','Traceability links received coffee, production batches, and finished products. Clear identifiers make investigation possible.','Trace one finished bag back to its roast batch and green lot.','A product name is a sufficient lot identifier.'],
 ['release','Release criteria','practice','qc','Release criteria define what a batch must satisfy before it is accepted. Document the measurements and sensory checks used.','Write a release checklist tied to one product’s target.','A curve match is sufficient for every release decision.'],
];
additions.push(
 ['drying','Drying','green','processing','Drying removes moisture after harvesting and processing. The drying method, handling, and recorded conditions help describe how the green coffee was prepared.','Document how one lot was dried and which conditions the producer monitored.','Drying and fermentation describe the same process.'],
 ['ethiopia','Ethiopia','green','origins','Explore Ethiopian lots through their producer or washing-station information, region, variety descriptions, and processing records. Treat each lot as a specific example rather than a national flavor template.','Compare two Ethiopian lot sheets and identify which details are documented and which are missing.','Every Ethiopian coffee should taste alike.'],
 ['kenya','Kenya','green','origins','Use Kenyan lot records to connect growing location, producer information, varieties, and processing with what you observe in the cup. Keep the roast and brewing context in your notes.','Compare two Kenyan samples with a consistent tasting preparation; record the lot differences before interpreting the cup.','Country of origin alone predicts a coffee’s acidity.'],
 ['panama','Panama','green','origins','Investigate a Panamanian lot at the farm and variety level. Separate the coffee’s documented identity from reputation, price, and your expectations.','Taste a coded Panamanian sample before reading its marketing description, then compare your observations.','A prestigious origin guarantees a particular flavor or quality.'],
 ['colombia','Colombia','green','origins','Compare Colombian lots using their regional, producer, variety, harvest, and processing information. A country label is a starting point for learning about the material.','Choose two Colombian lots and build a comparison of their documented growing and processing details.','All coffees from one country call for the same roast profile.'],
 ['experimental-processing','Experimental processing','green','processing','Experimental processing is a broad label for approaches beyond a producer’s usual practice. Ask for the actual sequence, conditions, and any introduced materials rather than inferring a method from the name.','Request a processing timeline for one experimental lot and distinguish documented steps from sensory claims.','Experimental processing describes one standardized method.'],
);
export const originExamples=['ethiopia','kenya','panama','colombia'];
const topicReasons:Record<string,string>={"species": "Species and variety information make a lot’s identity more precise.", "harvest": "Harvest observations help explain variation in the material before roasting.", "washed": "Understanding the process helps you interpret the supplier’s lot description.", "natural": "Drying and handling context helps you compare natural coffees thoughtfully.", "honey": "Producer-specific details prevent misleading comparisons based on labels alone.", "fermentation": "A process timeline separates documented handling from assumptions about flavor.", "screen-size": "Size distribution adds useful physical context alongside moisture and density.", "green-defects": "Consistent records help compare incoming lots and investigate quality issues.", "sample-roasting": "Repeatable sample preparation makes buying comparisons more dependable.", "green-storage": "Lot history helps you notice changes rather than attributing every difference to the roast.", "drum": "Knowing the machine’s design helps interpret its controls and response.", "fluid-bed": "Understanding airflow’s role helps explain how the system responds to adjustments.", "conduction": "Contact is one of the mechanisms behind energy transfer to the coffee.", "convection": "Air movement is part of the thermal process, not just exhaust management.", "radiation": "Recognizing multiple heat-transfer mechanisms improves your model of the machine.", "batch-mass": "A stable batch mass removes an avoidable source of variation.", "warm-up": "Repeatable initial conditions make roast comparisons easier to interpret.", "roast-color": "A consistent color measurement gives you another way to compare endpoints.", "weight-loss": "Mass loss provides a simple batch-level observation alongside color and tasting.", "grind": "Preparation variance can hide small sensory differences between roasts.", "brew-ratio": "A consistent ratio makes the tasting preparation easier to repeat.", "calibration": "Shared references improve the usefulness of tasting feedback.", "texture": "Separating tactile observations from flavor makes sensory targets clearer.", "replication": "Repeated trials help distinguish a consistent effect from ordinary variation.", "triangle": "A structured difference test asks a narrower question than a preference comparison.", "traceability": "Batch identifiers make quality investigations practical.", "release": "Defined criteria make acceptance decisions more consistent across batches."};
Object.assign(topicReasons,{drying:'Drying records add context that a fermentation label cannot provide.',
 ethiopia:'Lot-level detail helps turn an origin label into useful roasting context.',
 kenya:'Controlled comparisons help separate origin expectations from observations.',
 panama:'Blind observation helps limit reputation and price bias.',
 colombia:'Comparing lots reveals variation hidden by a country label.',
 'experimental-processing':'Clear processing records make unfamiliar labels more interpretable.',
});
for(const [id,title,domain,hub,summary,exercise,misconception] of additions){
 rows.push([id,title,domain,false,summary,topicReasons[id],exercise,misconception,[hub]]);
}

// Roast Transformation: a five-step route with supporting field notes.
rows.push(["roaster", "Coffee roaster", "roast", true, "Get to know the system that heats, moves, and measures your coffee. Roaster families describe designs, but actual machines often combine several mechanisms.", "Machine context comes before interpreting a roast curve.", "Sketch the heat source, bean movement, air path, and probe locations on your roaster.", "A machine category completely predicts its thermal behavior.", ["green-evaluation"]]);
rows.push(["air-roasters", "Air roasters", "roast", false, "Air roaster is a broad term for machines that rely strongly on heated air. Fluid-bed roasters are one overlapping family; the labels are not mutually exclusive.", "Design details are more useful than treating labels as rigid categories.", "Compare how two air-based machines move beans and control heat.", "Air roasters and fluid-bed roasters are always separate categories.", ["roaster"]]);
rows.push(["hybrid-roasters", "Hybrid roasters", "roast", false, "Hybrid is a useful descriptive label for machines combining chamber designs, agitation methods, or heat sources. Document the actual mechanisms rather than assuming one standard hybrid design.", "Modern machines often cross familiar categories.", "List the mechanisms combined in one modern roaster.", "Hybrid specifies one universal roaster architecture.", ["roaster"]]);
rows.push(["roast-drying", "Drying phase", "roast", false, "Early roasting heats the bean and removes moisture. Yellowing is a practical visual landmark, not proof that all water has left the bean.", "This provides the first reference point in a simple roast overview.", "Record charge, yellowing, and the uncertainty in observing color change.", "Water removal stops exactly at yellowing.", ["phases"]]);
rows.push(["browning-chemistry", "Browning chemistry", "roast", false, "Reducing sugars and amino compounds participate in Maillard reactions that contribute aroma compounds and brown melanoidins. Other reactions overlap; the named Maillard phase is an observation window, not a chemical on/off switch.", "A phase label cannot isolate one reaction or guarantee a flavor.", "Compare color and cup notes across repeat roasts without attributing a difference to one reaction alone.", "Maillard reactions occur only between yellowing and first crack.", ["maillard"]]);
rows.push(["sugar-breakdown", "Sugars & breakdown", "roast", false, "Sugars are transformed during roasting through several reaction pathways. Their products contribute to aroma and other compounds; perceived sweetness is not a direct reading of residual sugar.", "Sweetness in the cup cannot be prescribed by one phase duration.", "Compare perceived sweetness in coded samples at a consistent brew strength.", "A longer Maillard phase always means a sweeter cup.", ["maillard"]]);
rows.push(["chlorogenic-acids", "Chlorogenic acids (CGAs)", "roast", false, "Chlorogenic acids change and generally decline with increasing roast exposure, forming other compounds along the way. These changes do not occur at one universal phase boundary or probe temperature.", "Chemical measurements and sensory impressions answer different questions.", "Compare published measurements with their specific roast conditions before applying them to your machine.", "A particular displayed temperature removes all CGAs.", ["maillard"]]);
rows.push(["organic-acids", "Organic acids", "roast", false, "Different acids can form or break down as roasting proceeds. Their balance depends on the starting material and roast history; acidity in the cup is also shaped by extraction and perception.", "Acidity is not a single compound that disappears on a timer.", "Record acidity quality and intensity separately across a controlled roast comparison.", "All acids decline at the same rate throughout roasting.", ["maillard"]]);
rows.push(["aroma-formation", "Aroma formation & loss", "roast", false, "Roasting both creates and loses volatile aroma compounds. The balance evolves across overlapping reactions and changing conditions, rather than a list of flavors appearing at exact timestamps.", "An aroma category is a clue, not a unique chemical diagnosis.", "Track broad aroma changes during roasting and compare them with coded cup notes.", "One aroma note identifies one reaction at one exact stage.", ["maillard"]]);
rows.push(["development", "Development phase", "roast", false, "The interval from the observed onset of first crack to the endpoint is commonly called development. Reactions and structural changes continue, but development of the coffee is not confined to this interval.", "Time after crack is useful context alongside the full trajectory and endpoint.", "Compare time after first crack, total time, color, and cup notes together.", "Development-time ratio alone measures how well the center is roasted.", ["first-crack"]]);
rows.push(["internal-conduction", "Surface to center", "roast", false, "Heat flows inward along temperature gradients. The center responds with a delay: elapsed time matters alongside the surface-temperature history and the bean’s changing thermal properties.", "You control the surroundings more directly than the temperature at the center.", "Compare two temperature histories in a heat-transfer model and note why equal total time need not give equal center temperature.", "The center temperature is a function of time alone.", ["heat-transfer"]]);
rows.push(["bean-geometry", "Bean size & geometry", "roast", false, "Size and shape affect the distance heat must travel. In a simplified diffusion model, a characteristic heating time scales with distance squared divided by thermal diffusivity; real beans also lose moisture and change structure.", "Size can matter even when the external heating looks similar.", "Compare thickness and shape across lots before attributing a response only to origin or variety.", "All beans of the same mass have the same internal heating behavior.", ["internal-conduction"]]);
rows.push(["thermal-properties", "Density, moisture & structure", "roast", false, "Conductivity, heat capacity, density, moisture, and pore structure influence internal heating. These properties change during roasting; green bulk density alone does not specify thermal diffusivity.", "A single green measurement cannot predict the whole internal temperature field.", "Record bean size, moisture, and density separately when comparing roast responses.", "Denser green coffee always needs one fixed heat adjustment.", ["internal-conduction"]]);
rows.push(["thermal-time", "Time & temperature gradients", "roast", false, "Raising external heat can increase the surface-to-center temperature difference. It does not instantly heat the center, and may change the surface much faster. Interpret internal heating through both time and boundary conditions.", "More external power is not an independent control for the bean’s center.", "Design a comparison that records total time, endpoint, and sensory results rather than only power settings.", "Extra power instantly eliminates the internal heating delay.", ["internal-conduction"]]);
rows.push(["profile-template", "Parameterized template", "roast", false, "Define a reusable profile template with named inputs: batch mass, initial machine state, energy and airflow steps, event references, and endpoint criteria. Version the template and record actual values.", "Explicit parameters turn a one-off roast into a reproducible experiment.", "Create a baseline template and a copy that changes one named parameter.", "Copying a curve alone captures every condition needed to repeat a roast.", ["baseline"]]);
rows.push(["profile-matrix", "A matrix of profiles", "roast", false, "Build a small planned set of parameter combinations around a repeatable baseline. Attach lot, machine, template version, measurements, rest age, and blind sensory results to each run; include repeats.", "A profile matrix makes comparisons traceable and supports data-informed decisions.", "Start with two settings of one parameter and repeated baseline runs; compare against predefined cup criteria before expanding.", "A matrix of unreplicated roasts proves which parameter caused a flavor.", ["profile-template", "target"]]);
rows.push(["co2", "CO₂ & degassing", "roast", false, "Roasting generates gases, including CO₂, some of which remain in the bean and escape during storage, grinding, and brewing. Release rates vary with roast and storage conditions.", "Gas release changes brewing behavior and is one part of resting.", "Compare the same roast at recorded rest ages with a consistent brewing method.", "All coffees finish degassing after the same number of days.", ["cooling"]]);
rows.push(["oxidation", "Oxidation & aroma change", "roast", false, "Exposure to oxygen contributes to changes in roasted coffee during storage. Packaging, temperature, and handling affect the outcome; resting includes competing changes rather than endless improvement.", "Degassing and staling should not be treated as the same process.", "Compare matched portions stored under documented conditions and taste them blind.", "More rest always improves coffee.", ["cooling"]]);
rows.push(["resting-window", "Finding the resting window", "roast", false, "Build a lot-specific record of when your coffee tastes best for its intended brewing method. Coffee with Dongze field notes can document early cups to avoid, preferred windows, and later decline; personal results will be added from actual tastings.", "A useful window comes from repeated observations under stated conditions.", "Record roast ID, packaging, storage, rest age, recipe, and cup notes at several intervals. Mark the preferred window and uncertainty.", "One universal rest window applies to every coffee and brew method.", ["cooling"]]);
const updateRoast=(id:string,values:Partial<{title:string;core:boolean;summary:string;prerequisites:string[]}>)=>{
 const row=rows.find(r=>r[0]===id)!;
 if(values.title!==undefined)row[1]=values.title;
 if(values.core!==undefined)row[3]=values.core;
 if(values.summary!==undefined)row[4]=values.summary;
 if(values.prerequisites)row[8]=values.prerequisites;
};
updateRoast('target',{core:false,prerequisites:['baseline']});
updateRoast('machines',{prerequisites:['roaster']});
updateRoast('drum',{prerequisites:['roaster']});
updateRoast('fluid-bed',{prerequisites:['roaster']});
updateRoast('phases',{prerequisites:['roaster'],summary:'Follow a simple overview from drying and yellowing through browning, first crack, and development. These are useful landmarks in a continuous process: moisture loss and chemical reactions overlap.'});
updateRoast('maillard',{title:'Maillard phase',summary:'The browning interval, often described from yellowing to first crack, is a useful observational phase. Explore the chemistry below, remembering that these transformations overlap other phases and have no universal probe-temperature boundaries.'});
updateRoast('first-crack',{core:false});
updateRoast('heat-transfer',{prerequisites:['phases']});
updateRoast('sensors',{summary:'A probe samples a small part of the roasting system and responds with its own thermal lag. Position, airflow, contact, and instrument settings shape the reading. We use these observations to test hypotheses about the whole system; they do not directly reveal every bean or its center.'});
updateRoast('baseline',{title:'Profile building',summary:'Begin with an intended cup, batch size, and repeatable machine state. Turn controls and endpoints into named parameters, then build a matrix of recorded profiles and sensory outcomes. Repetition and controlled comparisons make the data interpretable.'});
updateRoast('endpoint',{core:false,prerequisites:['baseline']});
updateRoast('batch-mass',{title:'Batch size'});
updateRoast('cooling',{title:'Coffee resting',summary:'After roasting, gas release and storage-related changes affect brewing and sensory expression. Explore CO₂, oxidation, and a resting window established for each coffee and brewing method.',prerequisites:['baseline','endpoint']});
const roastOrder=['roaster','phases','heat-transfer','baseline','cooling'];
rows.sort((a,b)=>{
 const domainsOrder=['green','roast','sensory','practice'];
 const domainDifference=domainsOrder.indexOf(a[2])-domainsOrder.indexOf(b[2]);
 if(domainDifference)return domainDifference;
 if(a[2]!=='roast')return 0;
 return (roastOrder.includes(a[0])?roastOrder.indexOf(a[0]):-1+100)-(roastOrder.includes(b[0])?roastOrder.indexOf(b[0]):-1+100);
});

// Sensory comparisons connect roast parameters to a brewed outcome.
{const row=rows.find(r=>r[0]==="cupping")!; row[1]="Consistent brewing";row[4]="Choose one repeatable preparation for a comparison: cupping / immersion or the intended customer recipe. Keep water, grind, ratio, rest age, and handling consistent within that comparison. Each method answers a somewhat different question.";row[5]="A repeatable brew makes differences between roast candidates easier to interpret.";row[6]="Brew duplicate coded samples with one documented method before comparing profiles.";row[7]="One brewing method reveals every possible expression of a coffee.";}
{const row=rows.find(r=>r[0]==="sensory-language")!; row[1]="Sensory vocabulary";row[4]="Think in multiple sensory coordinates: acidity, sweetness, floral intensity, fruit intensity, texture, clarity, and unwanted characteristics. Shared descriptors and anchored scales let you compare relative positions, not just collect flavor words.";row[5]="A sensory vector describes a cup; the target determines which direction is desirable.";row[6]="Rate two coded cups on the same anchored scales and describe their relative differences.";row[7]="A higher number on every sensory axis always means a better coffee.";}
{const row=rows.find(r=>r[0]==="blind-tasting")!; row[1]="Matrix comparison";row[4]="Compare a planned array of profiles applied to the same lot, using a fixed brewing protocol and matched rest ages. Record a sensory vector for each candidate across hot, warm, and cool tastings. Look for useful trade-offs rather than a single impressive sip.";row[5]="A structured comparison helps navigate the coffee’s response to profile changes.";row[6]="Build a table with profile IDs as rows and sensory axes at each tasting stage as columns. Include a repeated baseline.";row[7]="A single sip or one winning attribute establishes the best profile.";}
{const row=rows.find(r=>r[0]==="evaluate")!; row[1]="Evaluate & update";row[4]="Shortlist several candidates against your intended sensory target. Compare them blind, repeat the brewing, and revisit them across the intended resting window before choosing which profiles to keep or test next.";row[5]="A promising early cup may not be the strongest choice at drinking age.";row[6]="Choose two or three candidates and a baseline; schedule coded comparisons through their resting windows.";row[7]="The highest score immediately after roasting is the final winner.";}
{const row=rows.find(r=>r[0]==="experiment")!; row[1]="Explore & refine";row[4]="Two valid strategies are broad profile exploration and guided iteration. A matrix can map a wider range of responses; an informed starting point with small, measured changes can use less coffee. Choose the approach based on uncertainty, resources, and the question.";row[5]="Both strategies turn sensory observations into the next planned experiment.";row[6]="Choose a search strategy, name the parameters you will vary, and set a tasting and stopping rule.";row[7]="One search strategy always finds the best profile with the least coffee.";}
{const row=rows.find(r=>r[0]==="logging")!; row[1]="Roast & brew journal";row[4]="Link lot and profile version to actual roast observations, brewing recipe, rest age, tasting stage, sensory coordinates, and the next decision. Record unsuccessful trials as well as promising ones.";row[5]="Linked records connect the process you changed to the cup you evaluated.";row[6]="Create one record containing roast ID, brew ID, sensory notes, and your next hypothesis.";row[7]="A roast curve alone explains the sensory outcome.";}
{const row=rows.find(r=>r[0]==="qc")!; row[1]="Scaling to production";row[4]="Translate successful candidates from the sample roaster to the production machine, then verify them using the intended brewing and resting conditions. Keep lot traceability, repeatability checks, and sensory release criteria.";row[5]="A successful sample roast needs validation at the production scale.";row[6]="Compare sample and production batches blind at matched rest ages using the customer recipe.";row[7]="Copying a sample-roaster curve guarantees an equivalent production cup.";}
rows.push(["mapping-roast", "Green + profile → roasted coffee", "sensory", false, "A profile acts on a particular green coffee in a particular machine to change its physical and chemical state. Equal time or a similar curve is not proof of equivalent roasted material, even when some green measurements match.", "Separate the process settings from the resulting material.", "Record the lot, initial measurements, actual trajectory, and endpoint for two equal-duration roasts.", "Five minutes produces the same roast in every coffee.", ["cupping"]]);
rows.push(["mapping-brew", "Roasted coffee + brew → cup", "sensory", false, "The roasted material is then ground and brewed. Water, recipe, equipment, rest age, and tasting temperature shape the sensory result. Roasting affects flavor potential, but a profile is not a portable flavor prescription.", "Judge the combined roast and preparation that the customer will experience.", "Brew one roast with immersion and the intended recipe; note which sensory differences change.", "A profile directly specifies flavor regardless of brewing.", ["cupping"]]);
rows.push(["mapping-target", "Choose the sensory result", "sensory", false, "Search for a useful sensory region for this coffee and use case: a balance of acidity, sweetness, aroma, clarity, and acceptable texture with few unwanted characteristics. Different coffees can need different profiles even when some physical attributes look alike.", "The objective is a desired brewed outcome rather than a particular duration or curve shape.", "Write the target sensory ranges and brewing context before selecting a profile.", "Matching moisture and density guarantees the same chemical composition and flavor response.", ["cupping"]]);
rows.push(["immersion", "Cupping / immersion", "sensory", false, "Immersion offers a practical common preparation for comparing samples and returning to them as they cool. Grind and extraction still affect clarity and what you perceive; cupping does not reveal everything or remove brewing effects. Its result may differ from the customer’s recipe.", "It provides a repeatable comparison, with a defined preparation context.", "Use one grind, water, ratio, and tasting schedule for a coded flight. Record sediment or clarity effects.", "Cupping is an unfiltered measurement of the bean independent of brewing.", ["cupping"]]);
rows.push(["customer-recipe", "Customer recipe brewing", "sensory", false, "Prepare coffee as recommended to customers: for example, the same four-pour V60 recipe. This tests the intended experience and can reveal lost clarity or complexity that a cupping preparation did not show. Pouring and technique add variability, so repeat the preparation.", "Customer-like preparation reduces surprises between evaluation and use.", "Document brewer, filter, water, grind, ratio, four pour timings and amounts, and repeat brews.", "A good cupping result guarantees a good result with any customer recipe.", ["cupping"]]);
rows.push(["sensory-axes", "Acidity · sweetness · floral · fruit", "sensory", false, "Represent a cup with several descriptive axes. Rate intensity separately from liking: moderate acidity may fit one target, while higher acidity fits another. Add clarity, bitterness, astringency, or other relevant axes without collapsing them into one score.", "The relative pattern can be more informative than one flavor label.", "Use the same low, medium, and high references to compare two cups on four axes.", "The strongest intensity on every axis is always the goal.", ["sensory-language"]]);
rows.push(["relative-coordinates", "Relative sensory coordinates", "sensory", false, "Numbers are a consistent recording convention, not absolute truth. Stable anchors make relative comparisons useful across a session. Keep uncertainty and repeat ratings; changing scale definitions makes apparent distances misleading.", "A sensory vector is meaningful only in a shared measurement context.", "Record A=[2,4,1,3] and B=[3,4,2,2] on four agreed axes, then explain each difference in words.", "Any numerical distance between sensory vectors is automatically meaningful.", ["sensory-language"]]);
rows.push(["target-region", "Target ranges & trade-offs", "sensory", false, "Define acceptable ranges for desirable attributes and limits for unwanted characteristics. Several candidates may meet the target with different balances; preference and customer use determine which trade-offs matter.", "There can be several useful solutions instead of a universal best point.", "Write target ranges for acidity, sweetness, floral and fruit intensity, plus an astringency limit.", "A single overall score preserves all relevant sensory trade-offs.", ["sensory-language"]]);
rows.push(["comparison-matrix", "Profiles × sensory dimensions", "sensory", false, "Keep the lot fixed, label every profile, and compare under a common preparation. A table can hold sensory axes, rest age, tasting stage, and uncertainty for each profile. Use repeats and varied tasting order to reduce confounding.", "The matrix connects a known parameter change with an observed response.", "Compare a baseline and nearby profile variants with coded labels and a randomized serving order.", "More profiles automatically produce more reliable knowledge.", ["blind-tasting"]]);
rows.push(["temperature-flight", "Hot → warm → cool", "sensory", false, "Return to each cup several times as it cools. Record the same attributes at each stage and note how clarity, balance, and unwanted characteristics change. Define stages consistently enough to compare the flight.", "A cup is a changing experience rather than one measurement at one sip.", "Make separate hot, warm, and cool entries for every candidate; record temperature or elapsed time.", "The first sip adequately represents the whole drinking experience.", ["blind-tasting"]]);
rows.push(["shortlist", "Shortlist candidates", "sensory", false, "Keep several candidates that satisfy different parts of the intended target. Separate promising differences from uncertain ones, and decide what evidence the next comparison needs to supply.", "A shortlist avoids committing too early to a noisy winner.", "Select two or three profiles and explain the trade-off each preserves.", "Only the single highest initial rating deserves another test.", ["evaluate"]]);
rows.push(["blind-validation", "Blind comparison", "sensory", false, "Hide profile identities and vary serving order when validating finalists. Include repeat samples and record descriptions before preference; triangle tests can assess distinguishability, not which coffee is better.", "Blinding reduces expectation effects from knowing the roast settings.", "Have another person code finalists and a duplicate baseline, then compare notes before revealing labels.", "A triangle-test difference establishes preference or quality.", ["evaluate"]]);
rows.push(["rest-validation", "Validate the resting window", "sensory", false, "Revisit finalists at multiple ages across the intended drinking window, using matched storage and preparation. Compare at equal ages and document when each is preferred; do not assume its earliest ranking will persist.", "The chosen profile must work when people actually drink it.", "Schedule repeat tastings at several points in the expected window and record ranking changes.", "One tasting date proves which profile performs best throughout its life.", ["evaluate"]]);
rows.push(["broad-exploration", "Broad profile exploration", "practice", false, "Test a planned range of profile parameters to map the coffee’s response. This can reveal distinct promising regions, but consumes more coffee and evaluation effort. Use a manageable design and repeated reference batches.", "Broad exploration is useful when you have little confidence in a starting point.", "Choose a small matrix, allocate coffee for repeats, and define which sensory outcomes will guide narrowing.", "Trying many unrelated profiles makes a controlled experiment.", ["experiment"]]);
rows.push(["guided-iteration", "Guided iteration", "practice", false, "Begin with an educated profile based on the coffee, machine, and target. Brew and evaluate, choose a small directional change, and compare it with the baseline. Keep helpful changes, reverse unhelpful ones, and reduce the step near a promising region.", "This is a practical gradient-descent analogy, not a measured mathematical gradient.", "State one sensory gap, predict which parameter change may help, and test a nearby candidate with a repeat baseline.", "Each sensory observation points to one unambiguous parameter adjustment.", ["experiment"]]);
rows.push(["search-limits", "Recheck & change direction", "practice", false, "Sensory responses are noisy and parameters can interact. A locally promising profile need not be best elsewhere. Repeat uncertain results, occasionally test another region, and stop when improvements are too small or inconsistent for the intended use.", "Guided search needs checks against noise and local optima.", "Write a stopping rule and one condition that would trigger a wider exploratory test.", "Following one direction guarantees the global optimum.", ["experiment"]]);
rows.push(["one-variable", "Controlled parameter changes", "practice", false, "Changing one parameter at a time is useful for a local comparison. A planned factorial matrix can investigate multiple parameters and their interactions, provided combinations and repeats are designed and recorded deliberately.", "A matrix and a local single-variable test answer different experimental questions.", "Name the parameter being tested, hold other conditions steady, and include a baseline repeat.", "A matrix requires changing everything without control.", ["experiment"]]);

export const nestedTopicRows:Record<string,string[][]>={
 origins:[['ethiopia','kenya'],['panama','colombia']],
 maillard:[['browning-chemistry'],['sugar-breakdown'],['chlorogenic-acids'],['organic-acids'],['aroma-formation']],
 endpoint:[['roast-color','weight-loss']],
};

export type TopicCluster = {id:string;title:string;domain:Domain;hub:string;side:'left'|'right';offset:number;rows:string[][];x:number;y:number;width:number;height:number};
const clusterSpecs: Omit<TopicCluster,'x'|'y'|'width'|'height'>[] = [
 {id:'plant-origin',title:'The plant & its place',domain:'green',hub:'seed-to-cup',side:'left',offset:150,rows:[['origins'],['ethiopia','kenya'],['panama','colombia'],['varieties'],['harvest']]},
 {id:'post-harvest',title:'Post-harvest processing',domain:'green',hub:'processing',side:'right',offset:295,rows:[['washed'],['honey'],['natural'],['fermentation'],['drying'],['experimental-processing']]},
 {id:'physical',title:'Read the green',domain:'green',hub:'physical-attributes',side:'left',offset:540,rows:[['moisture'],['water-activity'],['density'],['green-defects']]},
 {id:'buying',title:'From sample to inventory',domain:'green',hub:'green-evaluation',side:'right',offset:850,rows:[['sample-roasting'],['green-storage']]},
 {id:'equipment',title:'Roaster architecture',domain:'roast',hub:'roaster',side:'left',offset:155,rows:[['machines'],['drum','fluid-bed'],['air-roasters','hybrid-roasters']]},
 {id:'phase-overview',title:'What happens during a roast',domain:'roast',hub:'phases',side:'right',offset:420,rows:[['roast-drying'],['maillard'],...nestedTopicRows.maillard,['first-crack'],['development']]},
 {id:'thermal',title:'How heat reaches the bean',domain:'roast',hub:'heat-transfer',side:'right',offset:1090,rows:[['conduction','convection'],['radiation'],['sensors']]},
 {id:'bean-interior',title:'Heat inside the bean',domain:'roast',hub:'heat-transfer',side:'left',offset:1000,rows:[['internal-conduction'],['bean-geometry'],['thermal-properties'],['thermal-time']]},
 {id:'controls',title:'Build a reusable profile',domain:'roast',hub:'baseline',side:'left',offset:1450,rows:[['target'],['batch-mass'],['warm-up'],['profile-template'],['profile-matrix']]},
 {id:'outcomes',title:'Controls & endpoints',domain:'roast',hub:'baseline',side:'right',offset:1450,rows:[['airflow'],['ror'],['endpoint'],...nestedTopicRows.endpoint]},
 {id:'resting',title:'From roast to drinking window',domain:'roast',hub:'cooling',side:'right',offset:1990,rows:[['co2'],['oxidation'],['resting-window']]},
 {id:'mapping',title:'A profile is not a flavor',domain:'sensory',hub:'cupping',side:'right',offset:145,rows:[['mapping-roast'],['mapping-brew'],['mapping-target']]},
 {id:'preparation',title:'A consistent measurement',domain:'sensory',hub:'cupping',side:'left',offset:420,rows:[['water'],['grind','brew-ratio']]},
 {id:'brew-methods',title:'Choose a comparison method',domain:'sensory',hub:'cupping',side:'right',offset:440,rows:[['immersion'],['customer-recipe']]},
 {id:'language',title:'Build your sensory coordinates',domain:'sensory',hub:'sensory-language',side:'left',offset:780,rows:[['sensory-axes'],['relative-coordinates'],['target-region'],['calibration','texture']]},
 {id:'interpretation',title:'Read the whole comparison',domain:'sensory',hub:'blind-tasting',side:'right',offset:1130,rows:[['comparison-matrix'],['temperature-flight'],['attribution']]},
 {id:'validation',title:'Choose, validate & revisit',domain:'sensory',hub:'evaluate',side:'left',offset:1460,rows:[['shortlist'],['blind-validation'],['rest-validation']]},
 {id:'method',title:'Keep the evidence connected',domain:'practice',hub:'experiment',side:'left',offset:145,rows:[['logging'],['one-variable'],['replication','triangle']]},
 {id:'search-strategies',title:'Two ways to find your profile',domain:'practice',hub:'experiment',side:'right',offset:145,rows:[['broad-exploration'],['guided-iteration'],['search-limits']]},
 {id:'production',title:'Make it repeatable at scale',domain:'practice',hub:'qc',side:'right',offset:660,rows:[['scale-up'],['traceability','release']]},
];
const coreOffsets:Record<string,number>={
 'seed-to-cup':240,processing:420,'physical-attributes':650,'green-evaluation':920,
 roaster:230,phases:650,'heat-transfer':1140,baseline:1620,cooling:2080,
 cupping:480,'sensory-language':890,'blind-tasting':1220,evaluate:1580,
 experiment:265,qc:720,
};
export const MAP_WIDTH=1080;
export const regionLayout: Record<Domain, { y: number; height: number; center: number }> = {} as Record<Domain, { y: number; height: number; center: number }>;
let regionY=20;
for(const domain of Object.keys(domains) as Domain[]){
 const coreBottom=Math.max(...rows.filter(r=>r[2]===domain&&r[3]).map(r=>coreOffsets[r[0]]+80));
 const clusterBottom=Math.max(...clusterSpecs.filter(c=>c.domain===domain).map(c=>c.offset+64+c.rows.length*60));
 const height=Math.max(coreBottom,clusterBottom)+65;
 regionLayout[domain]={y:regionY,height,center:regionY+height/2};regionY+=height+70;
}
export const clusters:TopicCluster[]=clusterSpecs.map(c=>({...c,x:c.side==='left'?35:715,y:regionLayout[c.domain].y+c.offset,width:330,height:64+c.rows.length*60}));
export const topics:Topic[]=rows.map(([id,title,domain,core,summary,why,exercise,misconception,prerequisites])=>{
 const major=['seed-to-cup','roaster','cupping','experiment'].includes(id);
 let width=major?270:240,height=major?80:66,x=540-width/2,y=regionLayout[domain].y+coreOffsets[id];
 if(!core){const c=clusters.find(c=>c.rows.flat().includes(id))!;const row=c.rows.findIndex(r=>r.includes(id));const cells=c.rows[row];const parent=Object.keys(nestedTopicRows).find(parent=>nestedTopicRows[parent].flat().includes(id));const nested=!!parent;const inset=nested?9:0;width=(306-inset*2-(cells.length-1)*8)/cells.length;height=52;x=c.x+12+inset+cells.indexOf(id)*(width+8);y=nested?c.y+103+(row-1)*60:c.y+52+row*60;}
 return {id,title,domain,core,summary,why,exercise,misconception,prerequisites,level:core?'Foundation':'Intermediate',x,y,width,height};
});
// Curated essentials follow each central concept before continuing down the spine.
const beginnerBranches:Record<string,string[]>={
 'seed-to-cup':['origins','ethiopia','kenya'],
 processing:['washed','natural','honey'],
 'physical-attributes':['moisture'],
 roaster:['drum','air-roasters'],
 phases:['maillard'],
 'heat-transfer':['conduction','convection','radiation'],
 baseline:['airflow','ror','endpoint','roast-color','weight-loss'],
 cooling:['co2'],
 cupping:['immersion','customer-recipe'],
 'sensory-language':['sensory-axes','relative-coordinates'],
 'blind-tasting':['temperature-flight'],
 evaluate:['blind-validation'],
 experiment:['logging'],
 qc:['scale-up'],
};
export const beginner=topics.filter(t=>t.core).flatMap(t=>[t.id,...(beginnerBranches[t.id]??[])]);

// Green Potential uses route-relative references; stable IDs still back saved progress.
const greenCodes:Record<string,string>={};
const greenCore=topics.filter(t=>t.domain==='green'&&t.core);
for(const [index,topic] of greenCore.entries()){
 const prefix=`G${String(index+1).padStart(2,'0')}`;greenCodes[topic.id]=prefix;
 const cluster=clusters.find(c=>c.hub===topic.id)!;
 const children=cluster.rows.flat().filter(id=>!originExamples.includes(id));
 children.forEach((id,i)=>greenCodes[id]=`${prefix}.${i+1}`);
}
originExamples.forEach((id,i)=>greenCodes[id]=`${greenCodes.origins}.${i+1}`);
export function topicCode(topic:Topic){
 return greenCodes[topic.id]??roastCodes[topic.id]??laterCodes[topic.id]??`${domains[topic.domain].code}.${String(topics.filter(t=>t.domain===topic.domain).findIndex(t=>t.id===topic.id)+1).padStart(2,'0')}`;
}

const roastCodes:Record<string,string>={};
for(const [i,id] of roastOrder.entries()){
 const prefix=`R${String(i+1).padStart(2,'0')}`;roastCodes[id]=prefix;
 const children=clusters.filter(c=>c.hub===id).flatMap(c=>c.rows.flat()).filter(id=>!Object.values(nestedTopicRows).flat(2).includes(id));
 children.forEach((child,j)=>{roastCodes[child]=`${prefix}.${j+1}`;
 nestedTopicRows[child]?.flat().forEach((nested,k)=>roastCodes[nested]=`${roastCodes[child]}.${k+1}`);
 });
}
export const roastReadings=[
 {title:'Heat and moisture transport inside a bean',url:'https://pubmed.ncbi.nlm.nih.gov/23967709/'},
 {title:'Changes in CGAs during roasting',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC7679248/'},
 {title:'Measuring roasted coffee degassing',url:'https://digitalcollection.zhaw.ch/items/4789f6f9-a182-4840-a313-54a3e8445aec'},
];

const laterCodes:Record<string,string>={};
for(const domain of ['sensory','practice'] as Domain[]){
 topics.filter(t=>t.domain===domain&&t.core).forEach((topic,i)=>{
  const prefix=`${domains[domain].code}${String(i+1).padStart(2,'0')}`;laterCodes[topic.id]=prefix;
  clusters.filter(c=>c.hub===topic.id).flatMap(c=>c.rows.flat()).forEach((id,j)=>laterCodes[id]=`${prefix}.${j+1}`);
 });
}
